CREATE TABLE Client
(
    client_id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name      VARCHAR(60) NOT NULL UNIQUE

);

CREATE TABLE BankAccount
(
    account_number VARCHAR(40) PRIMARY KEY,
    bank_name      VARCHAR(50),
    created_at     DATE,
    balance        DECIMAL(18, 2),
    currency       VARCHAR(3),
    owner_id       INT REFERENCES Client (client_id)

);

CREATE TABLE Transaction
(
    trans_id        INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    trans_date_time TIMESTAMP,
    trans_type      VARCHAR(30),
    trans_status    VARCHAR(30),
    source_account  VARCHAR(40) REFERENCES BankAccount (account_number),
    target_account  VARCHAR(40) REFERENCES BankAccount (account_number),
    amount          DECIMAL(18, 2),
    currency        VARCHAR(3)

);